# Generated by Django 5.1.6 on 2025-04-06 11:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('name_vi', models.CharField(blank=True, max_length=255, null=True)),
                ('tourism_type', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itineraries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('image_order', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='itinerary.location')),
            ],
            options={
                'db_table': 'images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItineraryLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_order', models.IntegerField()),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='itinerary.itinerary')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_locations', to='itinerary.location')),
            ],
            options={
                'db_table': 'itinerary_locations',
                'managed': True,
                'unique_together': {('itinerary', 'location')},
            },
        ),
    ]
