# Generated by Django 5.1.6 on 2025-04-17 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_api', '0003_alter_location_options_location_embed_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour_api.location'),
        ),
        migrations.AlterField(
            model_name='itinerarylocation',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tour_api.itinerary'),
        ),
        migrations.AlterField(
            model_name='itinerarylocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_locations', to='tour_api.location'),
        ),
    ]
